### PR TITLE
Added back the Show QR code button

### PR DESCRIPTION
**Pull request by bkeenke**
The "Show QR Code" button has been added again. since there is an AmnesiaWG application for iOS and Android, the following QR code is accepted there

### CODE REVIEW

**Comment by spcfox** [comment]
Have you tested this?

**Comment by bkeenke** [comment]
yes I checked, it works

**Comment by spcfox** [comment]
My Android AmneziaVPN app doesn't scan this code. I think it expects JSON
https://github.com/amnezia-vpn/amnezia-client/blob/393e2897843136d0ad70cdda6967494d8ab4440d/client/ui/controllers/importController.cpp#L198

**Comment by bkeenke** [comment]
as I wrote above this is for the AmnesiaWG application

https://github.com/amnezia-vpn/amneziawg-android

https://github.com/amnezia-vpn/awg-apple

**Comment by spcfox** [comment]
Oh, sorry, I realized it was a different app

**Comment by spcfox** [comment]
I'm not sure if it's useful
1. Most users use the AmneziaVPN app. Having a QR code that it can't scan can confuse them (like me)
2. The iOS version is archived and not supported

**Comment by bkeenke** [comment]
Okay, I got it, I'll try to implement a QR code to support AmneziaVPN

**Comment by spcfox** [comment]
Yeh, making a QR for AmneziaVPN would be really cool. But if you want to add a QR for AmneziaWG, you can write why you disagree with me. Maybe we could make both versions

**Comment by bkeenke** [comment]
For myself, I have already made amendments, I agree with you that users will be confused.
I have only one argument for now.
Now you can download the file, so there is no link in the form of VPN:// or a file with the extension file.vpn, so I would add QR codes. The QR code for AmneziaVPN has not yet been provided

**Comment by bkeenke** [comment]
> Yeh, making a QR for AmneziaVPN would be really cool. But if you want to add a QR for AmneziaWG, you can write why you disagree with me. Maybe we could make both versions

Having difficulty converting a json into a link, how do you feel about using python for this?

**Comment by spcfox** [comment]
> Having difficulty converting a json into a link, how do you feel about using python for this?

I would prefer to leave the project in js, but if you write a converter in python, I can rewrite it in js

**Pull request closed without merging**
